language: java

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
# 8
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8
    - env: JDK='OpenJDK 8'
      jdk: openjdk8
# 9
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9
    - env: JDK='OpenJDK 9'
      install: . ./install-jdk.sh -F 9
# 10
    - env: JDK='Oracle JDK 10'
      jdk: oraclejdk10
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
# 11
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
# Early Access
    - env: JDK='Oracle JDK EA'
      install: . ./install-jdk.sh -F ea -L BCL
    - env: JDK='OpenJDK EA'
      install: . ./install-jdk.sh -F ea -L GPL
  allow_failures:
    - env: JDK='Oracle JDK EA'
    - env: JDK='OpenJDK EA'

script: mvn help:all-profiles clean install clover:instrument clover:clover -e

after_success:
  - bash <(curl -s https://codecov.io/bash)