language: java

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9

matrix:
    include:
      - os: linux
        dist: trusty
      - os: linux
        dist: precise

install: mvn install -Dgpg.skip
script: mvn clean compile test