language: java

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9

os: linux

matrix:
  include:
    - os: linux
      dist: trusty
    - os: precise
      dist: trusty

install: mvn install -Dgpg.skip
script: mvn clean compile test