package com.github.carlopantaleo.jmodel.utils;

public class SharedConstants {
    public static final String AUTOGEN_WARN =
            "This file was generated by a tool. Any modification will be overwritten during the next build cycle.";
}
